version: '3.4'

services:

  reverseproxy:
   
    build:
      context: .
      dockerfile: APIGateways/nginx/nginx.Dockerfile

  cataloguedb:
    image: mongo

  basketdb:
    image: redis

  discountdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  #pgadmin:
  #  image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce
  
    
  catalogue.api:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services\Catalogue\Catalogue.API\Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services\Basket\Basket.API\Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services\Discount\Discount.API\Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services\Ordering\Ordering.API\Dockerfile

  #ocelotapigw:
  #  image: ${DOCKER_REGISTRY-}ocelotapigw
  #  build:
  #    context: .
  #    dockerfile: APIGateways/Ocelot.ApiGateway/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: Infrastructure/EShpper.Identity/Dockerfile
  

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  #pgadmin_data: