version: '3.4'

services:
  cataloguedb:
    container_name: cataloguedb
    restart: always
    ports:
     - "27017:27017"
    volumes:
     - /data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
     - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin1234
     - POSTGRES_DB=DiscountDb
    restart: always
    ports:
     - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data/

  orderdb:
    container_name: orderdb
    environment:
      SA_PASSWORD: "Ifeanyi1234567"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  pgadmin:
    container_name: pgadmin
    environment:
     - PGADMIN_DEFAULT_EMAIL=ifenwachukwu7@outlook.com
     - PGSDMIN_DEFAULT_PASSWORD=admin1234
     - POSTGRES_DB=DiscountDb
    restart: always
    ports:
     - "5050:80"
    env_file:
     - C:\Users\USER\Desktop\pgadmin.env
    volumes:
     - pgadmin_data:/root/.pgadmin


  portainer:
    container_name: portainer
    restart: always
    ports:
     - "8080:8000"
     - "9090:9000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer_data:/data
    

  
     
  catalogue.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://cataloguedb:27017"
      - "DatabaseSettings__DatabaseName=CatalogueDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
    depends_on:
      - cataloguedb
    ports:
       - "9000:80"

  
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings__ConnectionString=basketdb:6379"
      - "GrpcSettings__DiscountUrl=http://discount.api"
    depends_on:
      - basketdb
    ports:
       - "9001:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      #- "ElasticConfiguration__Uri=http://elasticsearch:9200"
      #- ASPNETCORE_URLS=http://*:9002          
    depends_on:
      - discountdb
    ports:
      - "9002:80"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=http://*:9003
      - "ConnectionStrings__OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Ifeanyi1234567"
      #- "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
      #- "ElasticConfiguration__Uri=http://elasticsearch:9200"
    depends_on:
      - orderdb
      #- rabbitmq
    ports:
      - "9003:80"