version: '3.4'

services:
  catalogue.api:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services\Catalogue\Catalogue.API\Dockerfile

  cataloguedb:
    image: mongo

volumes:
  mongo_data: