version: '3.4'

services:

  #reverseproxy:
  #  container_name: nginxgateway
  #  restart: always
  #  ports:
  #    - "44344:44344"
  #  depends_on:
  #    - identityserver
  #    - catalogue.api
  #    - basket.api
  #    - discount.api
  #    - ordering.api
  
  
     
  cataloguedb:
    container_name: cataloguedb
    restart: always
    ports:
     - "27017:27017"
    volumes:
     - /data/db

   basketdb:
     container_name: basketdb
     restart: always
     ports:
      - "6379:6379"

   discountdb:
     container_name: discountdb
     environment:
     - postgres_user=admin
     - postgres_password=admin1234
     - postgres_db=discountdb
     restart: always
     ports:
     - "5432:5432"
     volumes:
     - postgres_data:/var/lib/postgresql/data/

   orderdb:
     container_name: orderdb
     environment:
     sa_password: "ifeanyi1234567"
     accept_eula: "y"
     restart: always
     ports:
     - "1433:1433"

   rabbitmq:
     container_name: rabbitmq
     restart: always
     ports:
     - "5672:5672"
     - "15672:15672"

  #pgadmin:
  #  container_name: pgadmin
  #  environment:
  #   - PGADMIN_DEFAULT_EMAIL=ifenwachukwu7@outlook.com
  #   - PGSDMIN_DEFAULT_PASSWORD=admin1234
  #   - POSTGRES_DB=DiscountDb
  #  restart: always
  #  ports:
  #   - "5050:80"
  #  env_file:
  #   - C:\Users\USER\Desktop\pgadmin.env
  #  volumes:
  #   - pgadmin_data:/root/.pgadmin


  portainer:
    container_name: portainer
    restart: always
    ports:
     - "8080:8000"
     - "9090:9000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer_data:/data
    

  
     
  catalogue.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:9000
      - "DatabaseSettings__ConnectionString=mongodb://cataloguedb:27017"
      - "DatabaseSettings__DatabaseName=CatalogueDb"
      - "DatabaseSettings__CollectionName=Products"
      - "DatabaseSettings__BrandsCollection=Brands"
      - "DatabaseSettings__TypesCollection=Types"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
    depends_on:
      - cataloguedb
    ports:
       - "9000:80"

  
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:9001 
      - "CacheSettings__ConnectionString=basketdb:6379"
      - "GrpcSettings__DiscountUrl=http://discount.api"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
       - "9001:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:9002
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
              
    depends_on:
      - discountdb
    ports:
      - "9002:80"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:9003
      - "ConnectionStrings__OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Ifeanyi1234567"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration__Uri=http://elasticsearch:9200"
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "9003:80"

  #ocelotapigw:
  #  container_name: ocelotapigw
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development      
  #  depends_on:
  #    - identityserver
  #    - catalogue.api
  #    - basket.api
  #    - discount.api
  #    - ordering.api
  #  ports:
  #    - "9010:80"

  #identityserver:
  #  container_name: identityserver
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_URLS=http://*:9011 
  #  ports:
  #    - "9011:9011"

  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"    
